# How to merge addresses and polling locations

In [1]:
# Important imports
import pandas as pd
import numpy as np

#### Read in the csv files and store them in a Pandas dataframe.

In [2]:
precinct_polling_list = pd.read_csv('precinct_polling_list.csv')
precinct_polling_list.name = 'Precinct Polling List'
addresses = pd.read_csv('addresses.csv')
addresses.name = 'Addresses'

#### View the data to make sure it loaded correctly.

In [3]:
print(precinct_polling_list.name, ':')
display(precinct_polling_list.head())
print(addresses.name, ':')
display(addresses.head())

Precinct Polling List :

,Location Name,Street,City,State/ZIP,Country,Precinct
0,Yorkside Pizza,288 York Street,New Haven,CT 06511,USA,CON-069
1,Library,301-399 South Boulevard Drive,Bainbridge,GA 39819,USA,GEO-062
2,Luxury Boston,150-151 Tremont Street,Boston,MA 02111,USA,MAS-111
3,Ingleside Village Pizza,2395 Ingleside Avenue,Macon,GA 31204,USA,GEO-041
4,Pizza House,1007 Merchant Street,Ambridge,PA 15003,USA,MAS-018

Addresses :

                      Street  Apt       City State         Zip Precinct ID
0              7 BEACON BLVD  NaN    PEABODY    MA  01960-6303     025-090
1              1847 TOWER DR  NaN  STOUGHTON    WI  53589-3539     055-015
2       4628 GREEN VALLEY RD  NaN  FAIRFIELD    CA  94534-1368     006-009
3                14 HALET ST  NaN   PORTLAND    ME  04102-1734     023-089
4  1606 BLACKBURN HEIGHTS DR  NaN  SEWICKLEY    PA  15143-8626     042-018

Some of the data entries are incorrect. We need to fix them. Luckily, it is possible to infer what is wrong with them.

In [4]:
precinct_polling_list = pd.read_csv('precinct_polling_list.csv')
bad_data = precinct_polling_list.isna().any(axis=1) # Get rows where data didnt work
display(precinct_polling_list[bad_data])

,Location Name,Street,City,State/ZIP,Country,Precinct
6,Hearth Pizzeria,974 Great Plain Avenue Needham MA 02492,USA,MAS-006,NaN,NaN
13,Community Center,29 Godwin Avenue,Ridgewood NJ 07450,USA,NEWJ-000,NaN
23,Upper Crust Pizzeria,1782 Massachusetts Ave Cambridge MA 02140,USA,MAS-070,NaN,NaN
30,Ian's Pizza Milwaukee,2035 East North Avenue Milwaukee WI,53211,USA,WIS-067,NaN

In [5]:
# Hearth Pizzeria
precinct_polling_list.iloc[6][4:] = precinct_polling_list.iloc[6][2:4] # shift data over
precinct_polling_list.iloc[6]['State/ZIP'] = " ".join(precinct_polling_list.iloc[6]['Street'].split()[-2:])
precinct_polling_list.iloc[6]['City'] = precinct_polling_list.iloc[6]['Street'].split()[-3]
precinct_polling_list.iloc[6]['Street'] = " ".join(precinct_polling_list.iloc[6]['Street'].split()[:-3])

# Community Center
precinct_polling_list.iloc[13][4:] = precinct_polling_list.iloc[13][3:5] # shift data over
precinct_polling_list.iloc[13]['State/ZIP'] = " ".join(precinct_polling_list.iloc[13]['City'].split()[-2:])
precinct_polling_list.iloc[13]['City'] = precinct_polling_list.iloc[13]['City'].split()[0]

# Upper Crust Pizzeria (Same fn as Hearth)
precinct_polling_list.iloc[23][4:] = precinct_polling_list.iloc[23][2:4] # shift data over
precinct_polling_list.iloc[23]['State/ZIP'] = " ".join(precinct_polling_list.iloc[23]['Street'].split()[-2:])
precinct_polling_list.iloc[23]['City'] = precinct_polling_list.iloc[23]['Street'].split()[-3]
precinct_polling_list.iloc[23]['Street'] = " ".join(precinct_polling_list.iloc[23]['Street'].split()[:-3])

# Ian's Pizza Milwaukee
precinct_polling_list.iloc[30][4:] = precinct_polling_list.iloc[30][3:5] # shift data over
precinct_polling_list.iloc[30]['State/ZIP'] = " ".join([precinct_polling_list.iloc[30]['Street'].split()[-1],
                                                        precinct_polling_list.iloc[30]['City'].split()[-1]])
precinct_polling_list.iloc[30]['City'] = precinct_polling_list.iloc[30]['Street'].split()[-2]
precinct_polling_list.iloc[30]['Street'] = " ".join(precinct_polling_list.iloc[30]['Street'].split()[:-3])

Lastly, courthouse has an extra dash in the precinct code.

In [6]:
display(precinct_polling_list.iloc[[27]])

,Location Name,Street,City,State/ZIP,Country,Precinct
27,Courthouse,9600-9708 West Linebaugh Avenue,Westchase,FL 33626,USA,FLO--67

In [7]:
# Courthouse (extra dash)
precinct_polling_list['Precinct'] = precinct_polling_list['Precinct'].str.replace('--', '-0')

display(precinct_polling_list[bad_data])

,Location Name,Street,City,State/ZIP,Country,Precinct
6,Hearth Pizzeria,974 Great Plain Avenue,Needham,MA 02492,USA,MAS-006
13,Community Center,29 Godwin Avenue,Ridgewood,NJ 07450,USA,NEWJ-000
23,Upper Crust Pizzeria,1782 Massachusetts Ave,Cambridge,MA 02140,USA,MAS-070
30,Ian's Pizza Milwaukee,2035 East North,Milwaukee,WI 53211,USA,WIS-067

#### To make it easier to combine the tables, we can use the state fips codes

In [8]:
state_fips = pd.read_csv('state_fips.csv').set_index('stusps').astype(str)
state_fips.name = 'State Fips'
print(state_fips.name, ':')
display(state_fips.head())

State Fips :

            stname st
stusps
AL         Alabama  1
AK          Alaska  2
AZ         Arizona  4
AR        Arkansas  5
CA      California  6

Get the state and zip from the existing column.

In [9]:
precinct_polling_list['State'] = precinct_polling_list['State/ZIP'].str.split(expand=True)[0]
precinct_polling_list['ZIP'] = precinct_polling_list['State/ZIP'].str.split(expand=True)[1]
del(precinct_polling_list['State/ZIP'])

Join the state fips table with this for an accurate fips number.

In [10]:
precinct_polling_list = precinct_polling_list.join(state_fips, on='State')

Create a precinct id with state fips and precinct id to match the addresses table, then set it as index so we can join it later.

In [11]:
precinct_polling_list['Precinct ID'] = precinct_polling_list['st'].str.zfill(3) + '-' + precinct_polling_list['Precinct'].str.split('-', expand=True)[1]
precinct_polling_list = precinct_polling_list.set_index('Precinct ID')
display(precinct_polling_list.head())

,Location Name,Street,City,Country,Precinct,State,ZIP,stname,st
Precinct ID,,,,,,,,,
009-069,Yorkside Pizza,288 York Street,New Haven,USA,CON-069,CT,06511,Connecticut,9
013-062,Library,301-399 South Boulevard Drive,Bainbridge,USA,GEO-062,GA,39819,Georgia,13
025-111,Luxury Boston,150-151 Tremont Street,Boston,USA,MAS-111,MA,02111,Massachusetts,25
013-041,Ingleside Village Pizza,2395 Ingleside Avenue,Macon,USA,GEO-041,GA,31204,Georgia,13
042-018,Pizza House,1007 Merchant Street,Ambridge,USA,MAS-018,PA,15003,Pennsylvania,42

Join addresses table with the polling list using the precinct id we created.

In [12]:
addresses_temp = addresses.join(precinct_polling_list[['Location Name', 'Street', 'City']], on='Precinct ID', rsuffix ='_precinct')
display(addresses_temp.head())

,Street,Apt,City,State,Zip,Precinct ID,Location Name,Street_precinct,City_precinct
0,7 BEACON BLVD,NaN,PEABODY,MA,01960-6303,025-090,Stonewood Tavern,139 Lynnfield Street,Peabody
1,1847 TOWER DR,NaN,STOUGHTON,WI,53589-3539,055-015,Michelangelo's Coffee House,114 State Street,Madison
2,4628 GREEN VALLEY RD,NaN,FAIRFIELD,CA,94534-1368,006-009,Mary's Pizza Shack,3085 Jefferson Street,Napa
3,14 HALET ST,NaN,PORTLAND,ME,04102-1734,023-089,Elementaray School Auditorium,574 Congress Street,Portland
4,1606 BLACKBURN HEIGHTS DR,NaN,SEWICKLEY,PA,15143-8626,042-018,Pizza House,1007 Merchant Street,Ambridge

There are some NaNs in the join. This means there were some precinct IDs that we did not have in our table. Ex:

In [13]:
display(addresses_temp.iloc[[12]])

,Street,Apt,City,State,Zip,Precinct ID,Location Name,Street_precinct,City_precinct
12,2 Gunderson Road,NaN,WILMINGTON,MA,01887-1520,048-010,NaN,NaN,NaN

The MA fips is 25, not 48. We can construct our own Precinct ID if we trust the state field more than the precinct ID field.

In [14]:
addresses = addresses.join(state_fips, on='State')
addresses['Precinct ID'] = addresses['st'].str.zfill(3) + '-' + addresses['Precinct ID'].str.split('-', expand=True)[1]
addresses = addresses.join(precinct_polling_list[['Location Name', 'Street', 'City']], on='Precinct ID', rsuffix ='_precinct')
display(addresses)

,Street,Apt,City,State,Zip,Precinct ID,stname,st,Location Name,Street_precinct,City_precinct
0,7 BEACON BLVD,NaN,PEABODY,MA,01960-6303,025-090,Massachusetts,25,Stonewood Tavern,139 Lynnfield Street,Peabody
1,1847 TOWER DR,NaN,STOUGHTON,WI,53589-3539,055-015,Wisconsin,55,Michelangelo's Coffee House,114 State Street,Madison
2,4628 GREEN VALLEY RD,NaN,FAIRFIELD,CA,94534-1368,006-009,California,6,Mary's Pizza Shack,3085 Jefferson Street,Napa
3,14 HALET ST,NaN,PORTLAND,ME,04102-1734,023-089,Maine,23,Elementaray School Auditorium,574 Congress Street,Portland
4,1606 BLACKBURN HEIGHTS DR,NaN,SEWICKLEY,PA,15143-8626,042-018,Pennsylvania,42,Pizza House,1007 Merchant Street,Ambridge
5,405 LAUREL PL,NaN,MACON,GA,31220-8761,013-041,Georgia,13,Ingleside Village Pizza,2395 Ingleside Avenue,Macon
6,1011 VALENCIA AVE,NaN,CORAL GABLES,FL,33134-5536,012-051,Florida,12,Cre8tive Apparel,859 Washington Avenue,Miami Beach
7,43 BOYDEN ST,NaN,BROCKTON,MA,02302-2303,025-111,Massachusetts,25,Luxury Boston,150-151 Tremont Street,Boston
8,1051 E STEARNS AVE,APT 36,LA HABRA,CA,90631-4857,006-021,California,6,Higgins Building,108 West 2nd Street,Los Angeles
9,10 RUSTIC DR,NaN,N BRUNSWICK,NJ,08902-4706,034-010,NewJersey,34,Dolceria,180 Nassau Street,Princeton
10,719 ROSEWOOD DR,NaN,PALO ALTO,CA,94303-3638,006-041,California,6,Middle School Gym,443 Emerson Street,Palo Alto
11,5373 FOXHOUND WAY,NaN,SAN DIEGO,CA,92130-4834,006-032,California,6,Senior High School,563 Carlsbad Village Drive,Carlsbad
12,2 Gunderson Road,NaN,WILMINGTON,MA,01887-1520,025-010,Massachusetts,25,Sal's Pizza,328 Boston Road,Billerica
13,1272 BEACON ST,APT 1,BROOKLINE,MA,02446-3717,025-111,Massachusetts,25,Luxury Boston,150-151 Tremont Street,Boston
14,300 CHURCHILL RD,NaN,TEANECK,NJ,07666-3007,034-087,NewJersey,34,NaN,NaN,NaN
15,439 MATHER MAIL CTR,NaN,CAMBRIDGE,MA,02138-7570,025-070,Massachusetts,25,Upper Crust Pizzeria,1782 Massachusetts Ave,Cambridge
16,1228 E KRAMER CIR,NaN,MESA,AZ,85203-1941,004-067,Arizona,4,Organ Stop Pizza,1149 East Southern Avenue,Mesa
17,5261 LOCHLOY DR,NaN,EDINA,MN,55436-2023,027-028,Minnesota,27,Pizza Luce,210 Blake Road North,Hopkins
18,22 PIPING ROCK DR,NaN,OSSINING,NY,10562-2349,036-000,NewYork,36,NaN,NaN,NaN
19,10338 MILLPORT DR,NaN,TAMPA,FL,33626-1706,012-067,Florida,12,Courthouse,9600-9708 West Linebaugh Avenue,Westchase
20,1244 FAIRVIEW AVE,NaN,HAVERTOWN,PA,19083-4219,042-097,Pennsylvania,42,Pizza Brain,2313 Frankford Avenue,Philadelphia
21,193 WINDING RIVER RD,NaN,WELLESLEY,MA,02482-7319,025-006,Massachusetts,25,Hearth Pizzeria,974 Great Plain Avenue,Needham
22,9650 THACKERY SQ,NaN,FAIRFAX,VA,22032-2537,051-092,Virginia,51,YMCA,1101 South Joyce Street,Arlington
23,390 WINTHROP MAIL CTR,NaN,CAMBRIDGE,MA,02138-7578,025-070,Massachusetts,25,Upper Crust Pizzeria,1782 Massachusetts Ave,Cambridge
24,75 HUNTINGTON RD,NaN,NEWTON,MA,02458-2416,025-011,Massachusetts,25,NaN,NaN,NaN
25,15 HAMPTON DR,NaN,WOODBRIDGE,CT,06525-1540,009-069,Connecticut,9,Yorkside Pizza,288 York Street,New Haven
26,19 O KEEFE RD,NaN,BRIDGEWATER,NJ,08807-5694,034-010,NewJersey,34,Dolceria,180 Nassau Street,Princeton
27,49 CLOCK TOWER LN,NaN,OLD WESTBURY,NY,11568-1031,036-099,NewYork,36,Eddie's Pizza,2048 Hillside Avenue,New Hyde Park
28,18 ACORN LN,NaN,SCARBOROUGH,ME,04074-7518,023-089,Maine,23,Elementaray School Auditorium,574 Congress Street,Portland
29,2835 NORMAN DR,NaN,BROOKFIELD,WI,53045-3015,055-067,Wisconsin,55,Ian's Pizza Milwaukee,2035 East North,Milwaukee
30,17635 FAIRWAY CIR,NaN,MONTE SERENO,CA,95030-2212,006-000,California,6,The Pruneyard Shopping Center,1875 South Bascom Avenue,Campbell
31,25 DAISY LN,NaN,AMHERST,NY,14228-1262,036-072,NewYork,36,Tim Hortons,5110-5140 Main Street,Buffalo
32,107 REGENTS SQ,NaN,PEACHTREE CTY,GA,30269-4279,013-009,Georgia,13,Waffle House,6444-6544 Georgia 85,Riverdale
33,725 GARIBALDI ST SW,NaN,ATLANTA,GA,30310-2170,013-000,Georgia,13,Antico Pizza,1093 Hemphill Avenue Northwest,Atlanta
34,1006 CREST RIDGE DR,NaN,EAST POINT,GA,30344-5764,013-055,Georgia,13,Eye Etc,484 Moreland Avenue Northeast,Atlanta
35,1404 NELSON BLVD,NaN,ROCKFORD,IL,61104-4718,017-038,Illinois,17,SVL Productions,311 East State Street,Rockford
36,916 JULIA PL,NaN,BAINBRIDGE,GA,39819-4816,013-062,Georgia,13,Library,301-399 South Boulevard Drive,Bainbridge
37,3375 RILMAN RD NW,NaN,ATLANTA,GA,30327-1507,013-000,Georgia,13,Antico Pizza,1093 Hemphill Avenue Northwest,Atlanta
38,37 MORANG COVE RD,NaN,NOBLEBORO,ME,04555-9506,023-027,Maine,23,Augusta Civic Center Inn,110 Community Drive,Augusta
39,274 CABOT MAIL CTR,NaN,CAMBRIDGE,MA,02138-7535,025-076,Massachusetts,25,NaN,NaN,NaN
40,6 FOX RUN LN,NaN,MARBLEHEAD,MA,01945-2169,025-090,Massachusetts,25,Stonewood Tavern,139 Lynnfield Street,Peabody

There are other values which we could not find a precinct code for. It looks like we do not have that polling location, so we can leave the value as NaN.

#### We are done!

In [15]:
addresses.to_csv('addresses_with_polling.csv', index=False)

## Differences with more table entries

This would only be slightly harder if the tables were bigger. The basic strategy, to create a common precinct ID so that we can join the tables together, is the same, but the cleaning of the data becomes a lengthy task. Luckily, we can use the pandas `isna()` function to sort the dataframe by bad values to ease in cleaning. In the methods used above, I used python to fix the data, when it would have probably been easier to just add a few commas to the csv file.

***
# Problem 2 (Creating VIP Files)

## polling_location.txt

address_location_name,address_line1,address_line2,address_line3,address_city,address_state,address_zip,directions,polling_hours,photo_url,id

In [16]:
precinct_polling_list.head()

,Location Name,Street,City,Country,Precinct,State,ZIP,stname,st
Precinct ID,,,,,,,,,
009-069,Yorkside Pizza,288 York Street,New Haven,USA,CON-069,CT,06511,Connecticut,9
013-062,Library,301-399 South Boulevard Drive,Bainbridge,USA,GEO-062,GA,39819,Georgia,13
025-111,Luxury Boston,150-151 Tremont Street,Boston,USA,MAS-111,MA,02111,Massachusetts,25
013-041,Ingleside Village Pizza,2395 Ingleside Avenue,Macon,USA,GEO-041,GA,31204,Georgia,13
042-018,Pizza House,1007 Merchant Street,Ambridge,USA,MAS-018,PA,15003,Pennsylvania,42

In [17]:
polling_location = precinct_polling_list.sort_index().reset_index()
polling_location['id'] = polling_location.index

precinct_polling_location = polling_location[['id', 'Precinct ID']]

polling_location['address_line2'] = np.NaN
polling_location['address_line3'] = np.NaN
polling_location['directions'] = np.NaN
polling_location['polling_hours'] = np.NaN
polling_location['photo_url'] = np.NaN

polling_location = polling_location[['Location Name', 'Street', 'address_line2', 'address_line3',
                                     'City', 'State', 'ZIP', 'directions', 'polling_hours',
                                     'photo_url', 'id']]
polling_location.columns = ['address_location_name', 'address_line1', 'address_line2', 'address_line3',
                            'address_city', 'address_state', 'address_zip', 'directions', 'polling_hours',
                            'photo_url', 'id']

display(polling_location)
polling_location.to_csv('polling_location.txt', index=False)

,address_location_name,address_line1,address_line2,address_line3,address_city,address_state,address_zip,directions,polling_hours,photo_url,id
0,Organ Stop Pizza,1149 East Southern Avenue,NaN,NaN,Mesa,AZ,85204,NaN,NaN,NaN,0
1,The Pruneyard Shopping Center,1875 South Bascom Avenue,NaN,NaN,Campbell,CA,95008,NaN,NaN,NaN,1
2,Mary's Pizza Shack,3085 Jefferson Street,NaN,NaN,Napa,CA,94559,NaN,NaN,NaN,2
3,Higgins Building,108 West 2nd Street,NaN,NaN,Los Angeles,CA,90012,NaN,NaN,NaN,3
4,Senior High School,563 Carlsbad Village Drive,NaN,NaN,Carlsbad,CA,92008,NaN,NaN,NaN,4
5,Middle School Gym,443 Emerson Street,NaN,NaN,Palo Alto,CA,94301,NaN,NaN,NaN,5
6,Yorkside Pizza,288 York Street,NaN,NaN,New Haven,CT,06511,NaN,NaN,NaN,6
7,Cre8tive Apparel,859 Washington Avenue,NaN,NaN,Miami Beach,FL,33139,NaN,NaN,NaN,7
8,Courthouse,9600-9708 West Linebaugh Avenue,NaN,NaN,Westchase,FL,33626,NaN,NaN,NaN,8
9,Antico Pizza,1093 Hemphill Avenue Northwest,NaN,NaN,Atlanta,GA,30318,NaN,NaN,NaN,9
10,Waffle House,6444-6544 Georgia 85,NaN,NaN,Riverdale,GA,30274,NaN,NaN,NaN,10
11,Ingleside Village Pizza,2395 Ingleside Avenue,NaN,NaN,Macon,GA,31204,NaN,NaN,NaN,11
12,Eye Etc,484 Moreland Avenue Northeast,NaN,NaN,Atlanta,GA,30307,NaN,NaN,NaN,12
13,Library,301-399 South Boulevard Drive,NaN,NaN,Bainbridge,GA,39819,NaN,NaN,NaN,13
14,SVL Productions,311 East State Street,NaN,NaN,Rockford,IL,61104,NaN,NaN,NaN,14
15,Augusta Civic Center Inn,110 Community Drive,NaN,NaN,Augusta,ME,04330,NaN,NaN,NaN,15
16,Elementaray School Auditorium,574 Congress Street,NaN,NaN,Portland,ME,04101,NaN,NaN,NaN,16
17,Hearth Pizzeria,974 Great Plain Avenue,NaN,NaN,Needham,MA,02492,NaN,NaN,NaN,17
18,Sal's Pizza,328 Boston Road,NaN,NaN,Billerica,MA,01821,NaN,NaN,NaN,18
19,Upper Crust Pizzeria,1782 Massachusetts Ave,NaN,NaN,Cambridge,MA,02140,NaN,NaN,NaN,19
20,Stonewood Tavern,139 Lynnfield Street,NaN,NaN,Peabody,MA,01960,NaN,NaN,NaN,20
21,Luxury Boston,150-151 Tremont Street,NaN,NaN,Boston,MA,02111,NaN,NaN,NaN,21
22,Pizza Luce,210 Blake Road North,NaN,NaN,Hopkins,MN,55343,NaN,NaN,NaN,22
23,Community Center,29 Godwin Avenue,NaN,NaN,Ridgewood,NJ,07450,NaN,NaN,NaN,23
24,Dolceria,180 Nassau Street,NaN,NaN,Princeton,NJ,08542,NaN,NaN,NaN,24
25,Tim Hortons,5110-5140 Main Street,NaN,NaN,Buffalo,NY,14221,NaN,NaN,NaN,25
26,Artichoke Basille's Pizza,114 10th Avenue,NaN,NaN,New York,NY,10011,NaN,NaN,NaN,26
27,Eddie's Pizza,2048 Hillside Avenue,NaN,NaN,New Hyde Park,NY,11040,NaN,NaN,NaN,27
28,Pizza House,1007 Merchant Street,NaN,NaN,Ambridge,PA,15003,NaN,NaN,NaN,28
29,Pizza Brain,2313 Frankford Avenue,NaN,NaN,Philadelphia,PA,19125,NaN,NaN,NaN,29
30,YMCA,1101 South Joyce Street,NaN,NaN,Arlington,VA,22202,NaN,NaN,NaN,30
31,Michelangelo's Coffee House,114 State Street,NaN,NaN,Madison,WI,53703,NaN,NaN,NaN,31
32,Ian's Pizza Milwaukee,2035 East North,NaN,NaN,Milwaukee,WI,53211,NaN,NaN,NaN,32

## precinct.txt

name,number,locality_id,ward,mail_only,ballot_style_image_url,id

In [18]:
precinct = precinct_polling_location[['Precinct ID']]
#precinct['name'] = range(60, 60 + len(precinct))
precinct['number'] = np.NaN
precinct['locality_id'] = range(3000, 3000 + len(precinct))
precinct['ward'] = np.NaN
precinct['mail_only'] = np.NaN
precinct['ballot_style_image_url'] = np.NaN
precinct['id'] = range(900100, 900100 + len(precinct))
precinct.columns = ['name'] + list(precinct.columns[1:])
precinct_polling_location['Precinct ID'] = precinct['id']
display(precinct)
precinct.to_csv('precinct.txt', index=False)

,name,number,locality_id,ward,mail_only,ballot_style_image_url,id
0,004-067,NaN,3000,NaN,NaN,NaN,900100
1,006-000,NaN,3001,NaN,NaN,NaN,900101
2,006-009,NaN,3002,NaN,NaN,NaN,900102
3,006-021,NaN,3003,NaN,NaN,NaN,900103
4,006-032,NaN,3004,NaN,NaN,NaN,900104
5,006-041,NaN,3005,NaN,NaN,NaN,900105
6,009-069,NaN,3006,NaN,NaN,NaN,900106
7,012-051,NaN,3007,NaN,NaN,NaN,900107
8,012-067,NaN,3008,NaN,NaN,NaN,900108
9,013-000,NaN,3009,NaN,NaN,NaN,900109
10,013-009,NaN,3010,NaN,NaN,NaN,900110
11,013-041,NaN,3011,NaN,NaN,NaN,900111
12,013-055,NaN,3012,NaN,NaN,NaN,900112
13,013-062,NaN,3013,NaN,NaN,NaN,900113
14,017-038,NaN,3014,NaN,NaN,NaN,900114
15,023-027,NaN,3015,NaN,NaN,NaN,900115
16,023-089,NaN,3016,NaN,NaN,NaN,900116
17,025-006,NaN,3017,NaN,NaN,NaN,900117
18,025-010,NaN,3018,NaN,NaN,NaN,900118
19,025-070,NaN,3019,NaN,NaN,NaN,900119
20,025-090,NaN,3020,NaN,NaN,NaN,900120
21,025-111,NaN,3021,NaN,NaN,NaN,900121
22,027-028,NaN,3022,NaN,NaN,NaN,900122
23,034-000,NaN,3023,NaN,NaN,NaN,900123
24,034-010,NaN,3024,NaN,NaN,NaN,900124
25,036-072,NaN,3025,NaN,NaN,NaN,900125
26,036-087,NaN,3026,NaN,NaN,NaN,900126
27,036-099,NaN,3027,NaN,NaN,NaN,900127
28,042-018,NaN,3028,NaN,NaN,NaN,900128
29,042-097,NaN,3029,NaN,NaN,NaN,900129
30,051-092,NaN,3030,NaN,NaN,NaN,900130
31,055-015,NaN,3031,NaN,NaN,NaN,900131
32,055-067,NaN,3032,NaN,NaN,NaN,900132

## precinct_polling_location.txt

In [19]:
precinct_polling_location.columns = ['polling_location_id', 'precinct_id']
precinct_polling_location = precinct_polling_location[['precinct_id', 'polling_location_id']]
display(precinct_polling_location)
precinct_polling_location.to_csv('precinct_polling_location.txt', index=False)

    precinct_id  polling_location_id
0        900100                    0
1        900101                    1
2        900102                    2
3        900103                    3
4        900104                    4
5        900105                    5
6        900106                    6
7        900107                    7
8        900108                    8
9        900109                    9
10       900110                   10
11       900111                   11
12       900112                   12
13       900113                   13
14       900114                   14
15       900115                   15
16       900116                   16
17       900117                   17
18       900118                   18
19       900119                   19
20       900120                   20
21       900121                   21
22       900122                   22
23       900123                   23
24       900124                   24
25       900125                   25
26       900126                   26
27       900127                   27
28       900128                   28
29       900129                   29
30       900130                   30
31       900131                   31
32       900132                   32